### ISSUE TITLE
Fonts not loaded correctly

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-org.github.io#8]
**Problem**

It seems that a few fonts are not loaded properly.

**To Reproduce**

In the Developer Console you will get this error:

```
WorkSans-Regular-latin.woff2:1 Failed to load resource: the server responded with a status of 404 ()
Catamaran-ExtraBold-latin.woff2:1 Failed to load resource: the server responded with a status of 404 ()
WorkSans-ExtraBold-latin.woff2:1 Failed to load resource: the server responded with a status of 404 ()
Catamaran-SemiBold-latin.woff2:1 Failed to load resource: the server responded with a status of 404 ()
WorkSans-Medium-latin.woff2:1 Failed to load resource: the server responded with a status of 404 ()
```

The fonts are expected to be in this directory: https://consento.org/fonts/
But there is no such directory in `gh-pages` branch.

**Comment by martinheidegger** [comment]
I can confirm this issue. Marc, Tanja and me probably didn't notice because we all have that font installed locally and the system simply didn't need to download it.
